name: Build Project
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11] # Gradle 4 does not support 16...
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/jdks
            ~/.gradle/native
            ~/.gradle/wrapper
          key: ${{ runner.os }}-paper-2-${{ hashFiles('**/*.gradle*', 'gradle/**', 'gradle.properties') }}
          restore-keys: ${{ runner.os }}-paper-2
      - name: Patch and build
        run: |
          chmod u+x ./gradlew
          ./gradlew build --stacktrace
